version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: ./api-pontos-turisticos/Dockerfile
    restart: always
    ports:
      - "8005:8005"
    volumes:
      - dev-static-data:/vol/web
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    restart: always
    volumes:
      - dev-db-data:/var/lib/postgresql/data-dev
    environment:
      - PGPORT=${POSTGRES_PORT}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"

volumes:
  dev-db-data:
  dev-static-data:
