# Generated by Django 5.0.2 on 2024-02-19 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("atracoes", "0001_initial"),
        ("avaliacoes", "0001_initial"),
        ("comentarios", "0001_initial"),
        ("enderecos", "0002_alter_endereco_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocIdentificacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="PontoTuristico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("descricao", models.TextField()),
                ("aprovado", models.BooleanField(default=False)),
                (
                    "foto",
                    models.ImageField(
                        blank=True, null=True, upload_to="pontos_turisticos"
                    ),
                ),
                ("atracoes", models.ManyToManyField(to="atracoes.atracao")),
                ("avaliacoes", models.ManyToManyField(to="avaliacoes.avaliacao")),
                ("comentarios", models.ManyToManyField(to="comentarios.comentario")),
                (
                    "doc_identificacao",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pontos_turisticos.docidentificacao",
                    ),
                ),
                (
                    "endereco",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="enderecos.endereco",
                    ),
                ),
            ],
        ),
    ]
