# Generated by Django 5.0.2 on 2024-03-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("touristic_points", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="touristicpoint",
            name="total_reviews",
            field=models.IntegerField(default=0),
        ),
    ]
