# Generated by Django 5.0.2 on 2024-03-11 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "touristic_points",
            "0004_rename_reviews_touristicpoint_number_reviews_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="touristicpoint",
            old_name="number_reviews",
            new_name="users_reviews",
        ),
    ]
