# Generated by Django 5.0.2 on 2024-03-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("touristic_points", "0002_touristicpoint_total_reviews"),
    ]

    operations = [
        migrations.AddField(
            model_name="touristicpoint",
            name="reviews",
            field=models.IntegerField(default=0),
        ),
    ]
