# Generated by Django 5.0.2 on 2024-02-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField()),
                ("opening_hours", models.TextField()),
                ("minimum_age", models.PositiveIntegerField()),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="attraction"),
                ),
                (
                    "observation",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
            ],
        ),
    ]
