# Generated by Django 5.0.2 on 2024-02-25 14:08

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attractions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attraction",
            name="created_at",
            field=model_utils.fields.AutoCreatedField(
                db_index=True,
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="Criado em",
            ),
        ),
        migrations.AddField(
            model_name="attraction",
            name="deleted_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="attraction",
            name="updated_at",
            field=model_utils.fields.AutoLastModifiedField(
                db_index=True,
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="Modificado em",
            ),
        ),
    ]
