# Generated by Django 5.0.2 on 2024-03-06 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attractions", "0002_attraction_created_at_attraction_deleted_at_and_more"),
        ("touristic_points", "0002_rename_assessments_touristicpoint_reviews_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attraction",
            name="tourist_spot",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="touristic_points.touristicpoint",
            ),
        ),
    ]
