# Generated by Django 5.0.2 on 2024-02-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("complement", models.CharField(blank=True, max_length=150, null=True)),
                ("number", models.CharField(max_length=5)),
                ("district", models.CharField(max_length=32)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=50)),
                ("pais", models.CharField(max_length=70)),
                ("zip", models.CharField(max_length=9)),
                ("latitude", models.IntegerField(blank=True, null=True)),
                ("longitude", models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
