# Generated by Django 5.0.2 on 2024-02-25 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("address", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="address",
            old_name="pais",
            new_name="country",
        ),
    ]
