# Generated by Django 5.0.2 on 2024-02-25 14:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
        ("touristic_points", "0002_rename_assessments_touristicpoint_reviews_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="tourist_spot",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="touristic_points.touristicpoint",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="review",
            name="note",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.RegexValidator("\\b([0-9]|10)\\b")]
            ),
        ),
    ]
