# Generated by Django 5.0.2 on 2024-02-25 20:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_review_tourist_spot_alter_review_note"),
        ("touristic_points", "0002_rename_assessments_touristicpoint_reviews_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="review",
            unique_together={("user", "tourist_spot")},
        ),
    ]
